// <auto-generated />
using AssetManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619075630_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetManager.API.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            Name = "Hp Core i5 8Gen",
                            Price = 45999.00m,
                            SerialNumber = "HP12345"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            Name = "MacBook Pro M2",
                            Price = 185000.00m,
                            SerialNumber = "MAC9988"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 1,
                            Name = "Dell Latitude",
                            Price = 65000.00m,
                            SerialNumber = "DEL7766"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 3,
                            Name = "ThinkPad E14",
                            Price = 89000.00m,
                            SerialNumber = "THINK44"
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 2,
                            Name = "Linux Desktop",
                            Price = 99000.00m,
                            SerialNumber = "LNX890"
                        });
                });

            modelBuilder.Entity("AssetManager.API.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kazim@csnainc.com",
                            FirstName = "Kazim",
                            LastName = "Raza"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ali.haider@gmail.com",
                            FirstName = "Ali",
                            LastName = "Haider"
                        },
                        new
                        {
                            Id = 3,
                            Email = "zainab@company.com",
                            FirstName = "Zainab",
                            LastName = "Khan"
                        });
                });

            modelBuilder.Entity("AssetManager.API.Models.Asset", b =>
                {
                    b.HasOne("AssetManager.API.Models.Employee", "Employee")
                        .WithMany("Assets")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AssetManager.API.Models.Employee", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
